update workflow

diff --git a/.github/workflows/staging .yml b/.github/workflows/staging .yml
--- a/.github/workflows/staging .yml
+++ b/.github/workflows/staging .yml
@@ -1,7 +1,6 @@
 # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
 # More GitHub Actions for Azure: https://github.com/Azure/actions
 
-
 name: Build and deploy Node.js app to Azure Web App - poultry-app-staging
 
 on:
@@ -23,7 +22,7 @@ jobs:
       - name: Set up Node.js version
         uses: actions/setup-node@v3
         with:
-          node-version: '20.x'
+          node-version: "20.x"
 
       - name: npm install, build, and test front-end
         run: |
@@ -31,7 +30,7 @@ jobs:
           npm install
           npm run build
           npm run lint 
-          npm run test 
+          npm run test
 
       - name: npm install, build, and test back-end
         run: |
@@ -39,33 +38,42 @@ jobs:
           npm install
           npm run build --if-present
           npm run lint
-          npm run test 
+          npm run test
 
   deploy_to_staging:
     runs-on: ubuntu-latest
     needs: build
 
     steps:
-    
       # Checkout the latest code from the branch
       - name: Checkout code
-        uses: actions/checkout@v2    
+        uses: actions/checkout@v2
 
-       # Install SSH client on the runner
+        # Install SSH client on the runner
       - name: Install SSH Client
-        run: sudo apt-get update && sudo apt-get install -y sshpass  
+        run: sudo apt-get update && sudo apt-get install -y sshpass
 
       # SSH into the VM and execute the deployment steps
       - name: SSH and Deploy
         run: |
           sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} << 'EOF'
+            set -e
             cd /home/${{ secrets.VM_USERNAME }}/Poultry-Management-App_Group_BSE24-9
+            CURRENT_COMMIT=$(git rev-parse HEAD)
             git pull origin staging
             cd front-end && npm i
             npm run build  
             cd ../back-end && npm i
-            ls
             mkdir -p ../back-end/frontend/
             cp -R ../front-end/dist/* ../back-end/frontend/
+            pm2 delete back-end || true
+            pm2 start npm --name "back-end" -- start
+
+            if ! curl -f http://localhost:3000; then
+              echo "Deployment failed! Rolling back..." 
+              git reset --hard $CURRENT_COMMIT
+              git push origin HEAD --force
+              pm2 delete back-end || true
+              pm2 start npm --name back-end -- start
+            fi  
           EOF
-          
